### ISSUE TITLE
RPC error

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/ousd-analytics#129]
Seen in logs just now:

    2021-04-15 16:20:07 ousd-analytics[20210329t173345]  ERROR 2021-04-15 16:20:07,707 django.request Internal Server Error: /fetch
    2021-04-15 16:20:07 ousd-analytics[20210329t173345]  Traceback (most recent call last):
        File "/layers/google.python.pip/pip/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner      response = get_response(request)
        File "/layers/google.python.pip/pip/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response      response = wrapped_callback(request, *callback_args, **callback_kwargs)
        File "/srv/core/views.py", line 129, in fetch_transactions      refresh_transactions(latest - 2)
        File "/srv/core/blockchain/harvest/__init__.py", line 18, in refresh_transactions      ensure_latest_logs(block_number)
        File "/srv/core/blockchain/harvest/transactions.py", line 231, in ensure_latest_logs      download_logs_from_contract(contract, start_block, end_block)
        File "/srv/core/blockchain/harvest/transactions.py", line 216, in download_logs_from_contract      ensure_transaction_and_downstream(tx_hash)
        File "/srv/core/blockchain/harvest/transactions.py", line 128, in ensure_transaction_and_downstream      debug = debug_trace_transaction(tx_hash)
        File "/srv/core/blockchain/rpc.py", line 128, in debug_trace_transaction      return data.get("result", {})  AttributeError: 'NoneType' object has no attribute 'get'

**Comment by mikeshultz** [comment]
These are `trace_transaction` RPC calls failing

**Comment by mikeshultz** [comment]
Unable to repro on local.  Will have to come back to this.
