### ISSUE TITLE
Etherscan fetch error

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/ousd-analytics#220]
Seen in logs:

    Traceback (most recent call last):
      File "/layers/google.python.pip/pip/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
        response = get_response(request)
      File "/layers/google.python.pip/pip/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/srv/core/views.py", line 199, in fetch_transactions
        refresh_transactions(latest - 2)
      File "/srv/core/blockchain/harvest/__init__.py", line 20, in refresh_transactions
        ensure_all_transactions(block_number)
      File "/srv/core/blockchain/harvest/transactions.py", line 87, in ensure_all_transactions
        for tx in get_contract_transactions(
      File "/srv/core/etherscan.py", line 27, in get_contract_transactions
        raise Exception(
    Exception: Failed to fetch (502) transaction list from Etherscan

**Comment by micahalcorn** [comment]
Bump https://github.com/OriginProtocol/ousd-analytics/issues/214 🤷 I'm calling this a **P2** until we know more.
