### ISSUE TITLE
Handle E-mail errors

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/ousd-analytics#46]
Currently if there's an error in an E-mail action it will stop processing the following actions.  If E-mail does fail, it shouldn't impact the rest of the actions, but should still scream in the logs.

**Comment by mikeshultz** [comment]
Think this has been fixed.  E-mail auth settings weren't being set.  Will wait until a successful send before closing.

**Comment by mikeshultz** [comment]
Now we're being cut off early:

    Traceback (most recent call last):
        File "/layers/google.python.pip/pip/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner      response = get_response(request)
        File "/layers/google.python.pip/pip/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response      response = wrapped_callback(request, *callback_args, **callback_kwargs)
        File "/srv/notify/views.py", line 10, in run_triggers      run_all()
        File "/srv/notify/main.py", line 14, in run_all      execute_all_actions(actions)
        File "/srv/notify/actions/__init__.py", line 54, in execute_all_actions      act.execute()
        File "/srv/notify/actions/objects.py", line 36, in execute      send_mail(
        File "/layers/google.python.pip/pip/lib/python3.8/site-packages/django/core/mail/__init__.py", line 61, in send_mail      return mail.send()
        File "/layers/google.python.pip/pip/lib/python3.8/site-packages/django/core/mail/message.py", line 284, in send      return self.get_connection(fail_silently).send_messages([self])
        File "/layers/google.python.pip/pip/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages      new_conn_created = self.open()
        File "/layers/google.python.pip/pip/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 69, in open      self.connection.login(self.username, self.password)
        File "/opt/python3.8/lib/python3.8/smtplib.py", line 723, in login      (code, resp) = self.auth(
        File "/opt/python3.8/lib/python3.8/smtplib.py", line 635, in auth      (code, resp) = self.docmd("AUTH", mechanism + " " + response)
        File "/opt/python3.8/lib/python3.8/smtplib.py", line 425, in docmd      return self.getreply()
        File "/opt/python3.8/lib/python3.8/smtplib.py", line 398, in getreply      raise SMTPServerDisconnected("Connection unexpectedly closed")  smtplib.SMTPServerDisconnected: Connection unexpectedly closed
